// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdD3o_dTISacRP7WFlhOvHJ775CZEkZV0',
    appId: '1:421263862464:web:1e5272cc064e9e42e9db25',
    messagingSenderId: '421263862464',
    projectId: 'fir-demo-adf09',
    authDomain: 'fir-demo-adf09.firebaseapp.com',
    storageBucket: 'fir-demo-adf09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSzeNGMge593yNbSGFhyOU6gN-plIbVsA',
    appId: '1:96363802096:android:9e46ffdc0ad633e6520135',
    messagingSenderId: '96363802096',
    projectId: 'pushnotifications-a793a',
    storageBucket: 'pushnotifications-a793a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoITKKKuvjy9dlUWDVsjeb3hZJh2ltzBI',
    appId: '1:421263862464:ios:f48dfd08f04b69ece9db25',
    messagingSenderId: '421263862464',
    projectId: 'fir-demo-adf09',
    storageBucket: 'fir-demo-adf09.firebasestorage.app',
    iosBundleId: 'com.example.task4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoITKKKuvjy9dlUWDVsjeb3hZJh2ltzBI',
    appId: '1:421263862464:ios:f48dfd08f04b69ece9db25',
    messagingSenderId: '421263862464',
    projectId: 'fir-demo-adf09',
    storageBucket: 'fir-demo-adf09.firebasestorage.app',
    iosBundleId: 'com.example.task4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdD3o_dTISacRP7WFlhOvHJ775CZEkZV0',
    appId: '1:421263862464:web:3ae4f653bcd71193e9db25',
    messagingSenderId: '421263862464',
    projectId: 'fir-demo-adf09',
    authDomain: 'fir-demo-adf09.firebaseapp.com',
    storageBucket: 'fir-demo-adf09.firebasestorage.app',
  );
}
